pub mod comments;
mod conditional;
mod context;
mod csharp_archive;
mod csharp_crypto;
mod csharp_deserialization;
mod csharp_handoff;
mod csharp_identity;
mod csharp_ingress;
mod csharp_injection;
mod csharp_legacy_web;
mod csharp_mainstream;
mod csharp_model;
mod csharp_output;
mod csharp_privilege;
mod csharp_rpc;
mod csharp_sinks;
mod csharp_standalone;
mod csharp_streaming_upload;
mod dotnet_project;
mod embedded_javascript;
mod file_roles;
mod go_context;
mod go_filesystem;
mod go_grpc;
mod go_ldap;
mod go_policy;
mod go_vulnerability;
mod go_web;
mod identity_boundary;
mod java_context;
mod java_crypto;
mod java_filesystem;
mod java_identity;
mod java_ingress;
mod java_network;
mod java_output;
mod java_persistence;
mod java_security;
mod java_serialization;
mod java_sinks;
mod java_upload;
mod java_web_policy;
mod kotlin;
pub(crate) use kotlin::callable_range as kotlin_callable_range;
pub(crate) use kotlin::caller_facts as kotlin_caller_facts;
pub(crate) use kotlin::function_range as kotlin_function_range;
pub(crate) use kotlin::query_fact as kotlin_numeric_query_fact;
pub mod literals;
mod matcher;
mod native_allocation;
mod native_arithmetic;
mod native_buffer;
mod native_cpp_ownership;
mod native_domain_bounds;
mod native_drogon;
mod native_heap_lifetime;
mod native_invalidation;
mod native_libarchive;
mod native_libxml2;
mod native_lifetime;
mod native_loaded_extent;
mod native_multiplication;
mod native_ownership;
mod native_region_bounds;
mod native_remaining_input;
mod native_serialized_blob;
mod native_signedness;
mod native_state;
mod native_toctou;
mod node_browser;
mod node_context;
mod node_express;
mod node_fastify;
mod node_nest;
mod node_next_policy;
mod node_policy;
mod node_randomness;
mod node_serverless;
mod object_input;
mod password_lifecycle;
mod php;
mod python_context;
mod python_flask;
mod python_identity;
mod razor;
mod reachability;
mod rust_context;
mod rust_project;
mod scanner;
#[path = "sql_flow.rs"]
mod security_paths;
mod symbols;
mod webforms;

pub use scanner::{FileAnalysisProfile, ScanProfile};
pub(crate) use scanner::{read_secret_text, scan_profiled};
