use mehscan_engine::provenance::inspect;
use std::{
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

static NEXT_FIXTURE: AtomicU64 = AtomicU64::new(0);

struct Fixture(PathBuf);
impl Fixture {
    fn new() -> Self {
        let path = std::env::temp_dir().join(format!(
            "mehscan-provenance-{}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos(),
            NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&path).unwrap();
        Self(path)
    }
    fn write(&self, path: &str, source: &str) {
        let path = self.0.join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, source).unwrap();
    }
}
impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

#[test]
fn manifests_maps_and_headers_supply_candidates_without_folder_exclusions() {
    let f = Fixture::new();
    f.write("package.json", r#"{"main":"app.js","scripts":{"build":"node tools/build.js","start":"node tools/build.js","generate":"node ../outside.js"}}"#);
    f.write("app.js", "export const value = 1;");
    f.write("tools/build.js", "export const value = 1;");
    f.write("src/main.ts", "export const value = 1;");
    f.write("public/main.js", "export const value = 1;");
    f.write("public/main.js.map", r#"{"version":3,"file":"main.js","sources":["../src/main.ts","../../outside.ts","webpack:///virtual.ts"],"sourcesContent":["do not dump this"]}"#);
    f.write(
        "public/owned.js",
        "export const value = 'ordinary authored source';",
    );
    f.write("public/lib.js", "/*! library (https://example.org/lib)\n * Copyright maintainers */\nexport const value = 1;");
    f.write(
        "src/generated.go",
        "// Code generated by tool. DO NOT EDIT.\npackage example\n",
    );
    f.write("src/ordinary.js", "const text = '@generated';");
    let report = inspect(&f.0, None, None).unwrap();
    assert!(report.candidates_only);
    assert!(
        report
            .candidates
            .iter()
            .any(|c| c.path == "app.js" && c.suggested_lane == "application")
    );
    let scripts: Vec<_> = report
        .candidates
        .iter()
        .filter(|c| c.path == "tools/build.js")
        .collect();
    assert_eq!(
        scripts.len(),
        2,
        "retain conflicting runtime/build evidence"
    );
    let map = report
        .candidates
        .iter()
        .find(|c| c.evidence_kind == "source_map")
        .unwrap();
    assert_eq!(map.sources, ["src/main.ts"]);
    assert_eq!(map.unresolved_sources, 2);
    assert_eq!(
        map.unresolved_references,
        ["../../outside.ts", "webpack:///virtual.ts"]
    );
    assert!(
        report
            .candidates
            .iter()
            .any(|c| c.path == "public/lib.js" && c.evidence_kind == "distribution_header")
    );
    assert!(
        report
            .candidates
            .iter()
            .any(|c| c.path == "src/generated.go" && c.evidence_kind == "generated_header")
    );
    assert!(!report.candidates.iter().any(|c| matches!(
        c.path.as_str(),
        "public/owned.js" | "src/ordinary.js" | "outside.js"
    )));
    let json = serde_json::to_string(&report).unwrap();
    assert!(!json.contains("do not dump this"));
    assert!(
        report
            .candidates
            .iter()
            .all(|c| c.evidence_sha256.len() == 64)
    );
    let paths = std::collections::BTreeSet::from(["public/main.js".to_owned()]);
    let scoped =
        mehscan_engine::provenance::inspect_review_paths(&f.0, None, None, Some(&paths)).unwrap();
    assert!(scoped.inventory_scope_only);
    assert_eq!(scoped.header_files_inspected, 1);
    assert_eq!(scoped.candidates.len(), 1);
    assert_eq!(scoped.candidates[0].sources, ["src/main.ts"]);
    f.write(
        "public/wrong.js.map",
        r#"{"version":3,"file":"absent.js","sources":["../src/main.ts"]}"#,
    );
    f.write("public/wrong.js", "const value=1;");
    assert!(
        !inspect(&f.0, None, None)
            .unwrap()
            .candidates
            .iter()
            .any(|c| c.path == "public/wrong.js")
    );
    f.write(
        "public/short.map",
        r#"{"version":3,"sources":["../src/main.ts"]}"#,
    );
    f.write("public/short.js", "const value=1;");
    assert!(
        inspect(&f.0, None, None)
            .unwrap()
            .candidates
            .iter()
            .any(|c| c.path == "public/short.js")
    );
}

#[test]
fn respects_ignores_scopes_bounds_and_incomplete_inputs() {
    let f = Fixture::new();
    f.write(".ignore", "hidden/\n");
    f.write("hidden/secret.js", "// @generated\n");
    f.write("module/generated.cs", "// <auto-generated />\n");
    f.write("module-other/generated.rs", "// @generated\n");
    f.write("module/broken.js.map", "not JSON");
    f.write("module/huge.js.map", &" ".repeat(2 * 1024 * 1024 + 1));
    let report = inspect(&f.0, Some("module"), None).unwrap();
    assert_eq!(report.candidates.len(), 1);
    assert_eq!(report.candidates[0].path, "module/generated.cs");
    assert_eq!(report.skipped_inputs, 2);
    let limited = inspect(&f.0, None, Some(1)).unwrap();
    assert_eq!(limited.candidate_count, 2);
    assert!(limited.truncated);
    assert!(inspect(&f.0, Some("../outside"), None).is_err());
    assert!(inspect(&f.0, Some("C:/outside"), None).is_err());
    assert!(inspect(&f.0, None, Some(0)).is_err());
    assert!(inspect(Path::new(&f.0.join(".ignore")), None, None).is_err());
}
